Update patch set 1
Patch Set 1:

Seems like it fails because of:

 Error: Could not find 'pt-online-schema-change'.

I would have to add that utility in the releng/tox-mysql base image.

Patch-set: 1
Reviewer: Gerrit User 8161 <8161@e9e9afe9-4712-486d-8885-f54b72dd1951>
Reviewer: Gerrit User 2556 <2556@e9e9afe9-4712-486d-8885-f54b72dd1951>